<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\OpdSimulator.Core\OpdSimulator.Core.csproj" />
    <ProjectReference Include="..\OpdSimulator.Data\OpdSimulator.Data.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.3.3" />
    <PackageReference Include="Avalonia.Desktop" Version="11.3.3" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.3" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="LiveChartsCore.SkiaSharpView.Avalonia" Version="2.0.5" />
    <PackageReference Include="Serilog" Version="4.4.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="OpdSimulator.App.Tests" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="..\..\docs\USER_MANUAL.md"
                      LogicalName="OpdSimulator.App.Assets.UserManual.md"
                      Link="Assets\UserManual.md" />
  </ItemGroup>

</Project>